import { describe, expect, it } from "vitest";
import { messageFacts } from "../../src/storage/message-facts.js";

// Shapes here are copied from real archived records: claude-code writes
// {id,name,input} / {tool_use_id,is_error,content}; codex writes
// {call_id,name,arguments} / {call_id,output} with arguments as a JSON string.

const claudeUse = (name: string, input: unknown) =>
  JSON.stringify({ id: "toolu_01VQbWiHWjEA3CStjPxUrfSt", name, input });

const useFacts = (name: string, input: unknown) =>
  messageFacts("assistant", "tool_use", claudeUse(name, input));

describe("messageFacts", () => {
  it("reads id, name and target off a claude-code tool_use", () => {
    const facts = useFacts("Read", { file_path: "/a/b.ts" });
    expect(facts).toMatchObject({
      tool_use_id: "toolu_01VQbWiHWjEA3CStjPxUrfSt",
      tool_name: "Read",
      tool_target: "/a/b.ts",
      is_error: null,
    });
  });

  it("reads call_id, name and target off a codex tool_use", () => {
    const facts = messageFacts(
      "assistant",
      "tool_use",
      JSON.stringify({
        call_id: "call_rMXEMl9x6Wc7H9ujPIY6syLY",
        name: "exec_command",
        arguments: JSON.stringify({ cmd: "ls -la ~/.codex" }),
      }),
    );
    expect(facts).toMatchObject({
      tool_use_id: "call_rMXEMl9x6Wc7H9ujPIY6syLY",
      tool_name: "exec_command",
      tool_target: "ls -la ~/.codex",
    });
  });

  it("prefers a path over a command and flattens multi-line and argv targets", () => {
    expect(useFacts("Edit", { file_path: "/x.ts", command: "rm" }).tool_target).toBe("/x.ts");
    expect(useFacts("Bash", { command: "grep -n foo \\\n  bar" }).tool_target).toBe(
      "grep -n foo \\ bar",
    );
    expect(useFacts("shell", { command: ["bash", "-lc", "ls"] }).tool_target).toBe("bash -lc ls");
  });

  it("leaves the target null when a tool takes only prose", () => {
    const facts = useFacts("AskUserQuestion", { questions: [] });
    expect(facts.tool_name).toBe("AskUserQuestion");
    expect(facts.tool_target).toBeNull();
  });

  it("pairs a tool_result back to its call and records the failure flag", () => {
    const ok = messageFacts(
      "tool",
      "tool_result",
      JSON.stringify({ tool_use_id: "toolu_1", is_error: false, content: "done" }),
    );
    expect(ok).toMatchObject({ tool_use_id: "toolu_1", is_error: 0, tool_name: null });
    const bad = messageFacts(
      "tool",
      "tool_result",
      JSON.stringify({ tool_use_id: "toolu_1", is_error: true, content: "boom" }),
    );
    expect(bad.is_error).toBe(1);
  });

  it("derives failure from both codex exec preambles, and stays null otherwise", () => {
    const result = (output: string) =>
      messageFacts("tool", "tool_result", JSON.stringify({ call_id: "call_1", output })).is_error;
    expect(result("Exit code: 0\nWall time: 0.1 seconds\nOutput:\nhi\n")).toBe(0);
    expect(result("Exit code: 127\nWall time: 0.1 seconds\nOutput:\nnot found\n")).toBe(1);
    expect(result("Chunk ID: 3026\nWall time: 0.05 seconds\nProcess exited with code 0\n")).toBe(0);
    expect(result("Chunk ID: 3026\nWall time: 0.05 seconds\nProcess exited with code 2\n")).toBe(1);
    // Rejections and aborts say nothing about success: null, not a guess.
    expect(result("exec command rejected by user")).toBeNull();
    expect(result("Wall time: 9.6 seconds\naborted by user")).toBeNull();
  });

  it("survives unparseable or unfamiliar content without throwing", () => {
    expect(messageFacts("assistant", "tool_use", "not json")).toMatchObject({
      tool_use_id: null,
      tool_name: null,
      tool_target: null,
    });
    expect(messageFacts("assistant", "tool_use", JSON.stringify({ foo: 1 })).tool_name).toBeNull();
  });

  it("counts a typed user turn as a prompt", () => {
    expect(messageFacts("user", "message", "interview for next phase").is_prompt).toBe(true);
    expect(messageFacts("user", "message", "  continue\n").is_prompt).toBe(true);
  });

  it("rejects the harness-written user records that would corrupt the numbering", () => {
    const pseudo = [
      "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
      "<local-command-caveat>Caveat: The messages below were generated by the user…",
      "<local-command-stdout></local-command-stdout>",
      "<task-notification>agent finished</task-notification>",
      "<bash-input>ls</bash-input>",
      "<system-reminder>remember to…</system-reminder>",
      "[Request interrupted by user for tool use]",
      "<environment_context>\n  <cwd>/Users/iBert</cwd>\n</environment_context>",
      "<turn_aborted>\nThe user interrupted the previous turn on purpose.",
      "<recommended_plugins>\nHere is a list of plugins…",
      "# AGENTS.md instructions for /Users/iBert/Documents\n<INSTRUCTIONS>",
      "",
    ];
    for (const content of pseudo) {
      expect(messageFacts("user", "message", content).is_prompt, content.slice(0, 30)).toBe(false);
    }
  });

  it("counts nothing but a user message as a prompt", () => {
    expect(messageFacts("assistant", "message", "sure thing").is_prompt).toBe(false);
    expect(messageFacts("user", "tool_result", "{}").is_prompt).toBe(false);
    expect(messageFacts("system", "system", "hook fired").is_prompt).toBe(false);
  });
});
