//! Objective facts derived from a message's content blob at projection time.
//!
//! The event log keeps every message's full content, so these are re-derived
//! on every rebuild — a wrong call here costs a delete-and-rebuild, not a
//! migration. That is why only unambiguous facts are promoted: a tool's id,
//! name and target, whether a result reported failure, and whether a user
//! record is a real prompt. Anything requiring a judgement about conversation
//! structure (parenting, sidechains) stays out.
//!
//! Deliberately structural, not source-switched: `source` is free-form and new
//! harnesses appear, so each fact is read from whichever of the known field
//! spellings is present (claude-code's `id`/`tool_use_id`/`input`, codex's
//! `call_id`/`arguments`). An unrecognized shape yields nulls, never a panic.
//!
//! String handling mirrors JavaScript on purpose (its whitespace set, UTF-16
//! slicing): the archive's facts were first derived that way, and a rebuilt
//! index must derive the same ones.

use serde_json::{Map, Value};

use crate::js;

/// Longest tool_target retained. Full text stays searchable via FTS.
const MAX_TARGET: usize = 500;

/// Input keys that name *what* a call acted on, most specific first. Prose
/// keys (`description`, `prompt`, `explanation`) are deliberately excluded —
/// a target is an identifier you can filter on, not a sentence.
const TARGET_KEYS: [&str; 12] = [
    "file_path",
    "notebook_path",
    "path",
    "cmd",
    "command",
    "pattern",
    "url",
    "query",
    "skill",
    "subagent_type",
    "task_id",
    "taskId",
];

/// User records a harness writes on the user's behalf. These are not prompts:
/// counting them makes prompt numbering useless as an address, since a session
/// opens with several and picks up more on every slash command or
/// interruption. Matched as a prefix of the trimmed content.
const HARNESS_PREFIXES: [&str; 17] = [
    // claude-code
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<task-notification>",
    "<bash-input>",
    "<bash-stdout>",
    "<system-reminder>",
    "[Request interrupted",
    "Caveat: The messages below were generated by the user",
    // codex
    "<environment_context>",
    "<turn_aborted>",
    "<recommended_plugins>",
    "<user_instructions>",
    "<user_shell_command>",
    "# AGENTS.md instructions for",
];

/// The two preambles codex prints ahead of exec output, each followed by the
/// exit status.
const EXIT_PREAMBLES: [&str; 2] = ["Exit code: ", "Process exited with code "];

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MessageFacts {
    pub tool_use_id: Option<String>,
    pub tool_name: Option<String>,
    pub tool_target: Option<String>,
    /// 1 failed, 0 succeeded, None not determinable from the record.
    pub is_error: Option<i64>,
    /// True only for a user record the person actually typed.
    pub is_prompt: bool,
}

pub fn message_facts(role: &str, kind: &str, content: &str) -> MessageFacts {
    if kind == "tool_use" || kind == "tool_result" {
        return tool_facts(kind, content);
    }
    MessageFacts {
        is_prompt: role == "user" && kind == "message" && is_prompt(content),
        ..MessageFacts::default()
    }
}

fn tool_facts(kind: &str, content: &str) -> MessageFacts {
    let Some(blob) = js::parse_object_text(content) else {
        return MessageFacts::default();
    };
    if kind == "tool_result" {
        return MessageFacts {
            tool_use_id: string_at(&blob, &["tool_use_id", "call_id", "id"]),
            is_error: result_error(&blob),
            ..MessageFacts::default()
        };
    }
    let input = js::first_present(&blob, &["input", "arguments"]).and_then(js::parse_object);
    MessageFacts {
        tool_use_id: string_at(&blob, &["id", "call_id"]),
        tool_name: string_at(&blob, &["name"]),
        tool_target: input.as_ref().and_then(target),
        ..MessageFacts::default()
    }
}

/// A result's failure state. `is_error` is authoritative where a harness
/// records it; otherwise fall back to the exit status codex prints ahead of
/// the output. Records carrying neither (rejections, aborts, MCP payloads)
/// stay None rather than being guessed into a false negative.
fn result_error(blob: &Map<String, Value>) -> Option<i64> {
    if let Some(Value::Bool(flag)) = blob.get("is_error") {
        return Some(if *flag { 1 } else { 0 });
    }
    let output = js::first_present(blob, &["output", "content"])?.as_str()?;
    let code = exit_code(output)?;
    Some(if code == 0 { 0 } else { 1 })
}

/// The first line that opens with an exec preamble, and the digits after it.
fn exit_code(output: &str) -> Option<u64> {
    output.split(js::is_line_terminator).find_map(|line| {
        EXIT_PREAMBLES.iter().find_map(|preamble| {
            let digits: String =
                line.strip_prefix(preamble)?.chars().take_while(char::is_ascii_digit).collect();
            digits.parse().ok()
        })
    })
}

fn target(input: &Map<String, Value>) -> Option<String> {
    TARGET_KEYS.iter().find_map(|key| {
        let flat = flatten(input.get(*key)?)?;
        Some(js::slice_to(&flat, MAX_TARGET))
    })
}

/// Renders a target value as one line: codex passes argv arrays, not strings.
fn flatten(value: &Value) -> Option<String> {
    let raw = match value {
        Value::Array(items) => {
            items.iter().filter_map(string_or_number).collect::<Vec<_>>().join(" ")
        }
        other => string_or_number(other)?,
    };
    let collapsed = js::collapse_whitespace(&raw);
    if collapsed.is_empty() { None } else { Some(collapsed) }
}

fn string_or_number(value: &Value) -> Option<String> {
    match value {
        Value::String(s) => Some(s.clone()),
        Value::Number(n) => Some(js::number(n)),
        _ => None,
    }
}

/// The first present key's value if it is a non-empty string.
fn string_at(blob: &Map<String, Value>, keys: &[&str]) -> Option<String> {
    let value = js::first_present(blob, keys)?.as_str()?;
    if value.is_empty() { None } else { Some(value.to_string()) }
}

fn is_prompt(content: &str) -> bool {
    let trimmed = js::trim_start(content);
    if trimmed.is_empty() {
        return false;
    }
    !HARNESS_PREFIXES.iter().any(|prefix| trimmed.starts_with(prefix))
}
