// Objective facts derived from a message's content blob at projection time.
//
// The event log keeps every message's full content, so these are re-derived on
// every rebuild — a wrong call here costs a delete-and-rebuild, not a migration.
// That is why only unambiguous facts are promoted: a tool's id, name and target,
// whether a result reported failure, and whether a user record is a real prompt.
// Anything requiring a judgement about conversation structure (parenting,
// sidechains) stays out.
//
// Deliberately structural, not source-switched: `source` is free-form and new
// harnesses appear, so each fact is read from whichever of the known field
// spellings is present (claude-code's `id`/`tool_use_id`/`input`, codex's
// `call_id`/`arguments`). An unrecognized shape yields nulls, never a throw.

/** Longest tool_target retained. Full text stays searchable via FTS. */
const MAX_TARGET = 500;

/**
 * Input keys that name *what* a call acted on, most specific first. Prose keys
 * (`description`, `prompt`, `explanation`) are deliberately excluded — a target
 * is an identifier you can filter on, not a sentence.
 */
const TARGET_KEYS = [
  "file_path",
  "notebook_path",
  "path",
  "cmd",
  "command",
  "pattern",
  "url",
  "query",
  "skill",
  "subagent_type",
  "task_id",
  "taskId",
];

/**
 * User records a harness writes on the user's behalf. These are not prompts:
 * counting them makes prompt numbering useless as an address, since a session
 * opens with several and picks up more on every slash command or interruption.
 * Matched as a prefix of the trimmed content.
 */
const HARNESS_PREFIXES = [
  // claude-code
  "<command-name>",
  "<command-message>",
  "<command-args>",
  "<local-command-stdout>",
  "<local-command-caveat>",
  "<task-notification>",
  "<bash-input>",
  "<bash-stdout>",
  "<system-reminder>",
  "[Request interrupted",
  "Caveat: The messages below were generated by the user",
  // codex
  "<environment_context>",
  "<turn_aborted>",
  "<recommended_plugins>",
  "<user_instructions>",
  "<user_shell_command>",
  "# AGENTS.md instructions for",
];

/** Exit status as reported by codex's two exec output preambles. */
const EXIT_CODE = /(?:^Exit code: (\d+)|^Process exited with code (\d+))/m;

export interface MessageFacts {
  tool_use_id: string | null;
  tool_name: string | null;
  tool_target: string | null;
  /** 1 failed, 0 succeeded, null not determinable from the record. */
  is_error: number | null;
  /** True only for a user record the person actually typed. */
  is_prompt: boolean;
}

const NO_FACTS: MessageFacts = {
  tool_use_id: null,
  tool_name: null,
  tool_target: null,
  is_error: null,
  is_prompt: false,
};

export function messageFacts(role: string, kind: string, content: string): MessageFacts {
  if (kind === "tool_use" || kind === "tool_result") {
    return toolFacts(kind, content);
  }
  return { ...NO_FACTS, is_prompt: role === "user" && kind === "message" && isPrompt(content) };
}

function toolFacts(kind: string, content: string): MessageFacts {
  const blob = parseObject(content);
  if (!blob) return NO_FACTS;

  if (kind === "tool_result") {
    return {
      ...NO_FACTS,
      tool_use_id: str(blob["tool_use_id"] ?? blob["call_id"] ?? blob["id"]),
      is_error: resultError(blob),
    };
  }
  const input = parseObject(blob["input"] ?? blob["arguments"]);
  return {
    ...NO_FACTS,
    tool_use_id: str(blob["id"] ?? blob["call_id"]),
    tool_name: str(blob["name"]),
    tool_target: input ? target(input) : null,
  };
}

/**
 * A result's failure state. `is_error` is authoritative where a harness records
 * it; otherwise fall back to the exit status codex prints ahead of the output.
 * Records carrying neither (rejections, aborts, MCP payloads) stay null rather
 * than being guessed into a false negative.
 */
function resultError(blob: Record<string, unknown>): number | null {
  const flag = blob["is_error"];
  if (typeof flag === "boolean") return flag ? 1 : 0;
  const output = blob["output"] ?? blob["content"];
  if (typeof output !== "string") return null;
  const match = EXIT_CODE.exec(output);
  if (!match) return null;
  return Number(match[1] ?? match[2]) === 0 ? 0 : 1;
}

function target(input: Record<string, unknown>): string | null {
  for (const key of TARGET_KEYS) {
    if (!(key in input)) continue;
    const flat = flatten(input[key]);
    if (flat !== null) return flat.length > MAX_TARGET ? flat.slice(0, MAX_TARGET) : flat;
  }
  return null;
}

/** Renders a target value as one line: codex passes argv arrays, not strings. */
function flatten(value: unknown): string | null {
  const raw = Array.isArray(value)
    ? value.filter((v) => typeof v === "string" || typeof v === "number").join(" ")
    : typeof value === "string" || typeof value === "number"
      ? String(value)
      : null;
  if (raw === null) return null;
  const collapsed = raw.replace(/\s+/g, " ").trim();
  return collapsed === "" ? null : collapsed;
}

/** JSON objects arrive both parsed and as nested strings (codex `arguments`). */
function parseObject(value: unknown): Record<string, unknown> | null {
  if (typeof value === "string") {
    try {
      return parseObject(JSON.parse(value));
    } catch {
      return null;
    }
  }
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  return null;
}

function str(value: unknown): string | null {
  return typeof value === "string" && value !== "" ? value : null;
}

function isPrompt(content: string): boolean {
  const trimmed = content.trimStart();
  if (trimmed === "") return false;
  return !HARNESS_PREFIXES.some((prefix) => trimmed.startsWith(prefix));
}
